[tool.kedro]
package_name = "garden_of_forking_moose"
project_name = "garden-of-forking-moose"
kedro_init_version = "0.18.13"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/garden_of_forking_moose -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
